### ISSUE TITLE
Doesn't respect display aspect ratio

### ISSUE THREAD

**Issue by cassidyjames** [elementary/videos#108] opened 2018-10-30 02:18 UTC
If a video file has Display Aspect Ratio (DAR) metadata set—i.e. an anamorphic video shot on a 16:9 sensor—Videos does not properly scale the output to the correct ratio. This results in squeezed footage. VLC, for example, reads this data and de-squeezes the file for playback.

**Comment by davidmhewitt** [comment] 2019-05-22 11:16
I've just been investigating this as I've just found the same issue. It appears to be caused by ClutterGst, I've raised an issue upstream here:
https://gitlab.gnome.org/GNOME/clutter-gst/issues/6

**Comment by selwynorren** [comment] 2021-07-27 15:30
Hey All,

I still seem to be having this issue. Is there something I am missing here or something I need to install?

**Comment by mroi** [comment] 2023-08-20 09:42
The aspect ratio for previously problematic videos is now correct in the current Flatpak release (version 3.0.0). Has this been fixed?

**Comment by danirabbit** [comment] 2023-08-20 22:09
Most likely since we're no longer using clutter 🎉 

Closing as fixed :)

**Closed** 2023-08-20 22:09 UTC
Labels: Status: Confirmed
