### ISSUE TITLE
Launching application does nothing except consume CPU

### ISSUE THREAD

**Issue by jtrees** [elementary/videos#137] opened 2019-10-06 17:13 UTC
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
The application cannot be started at all, regardless of whether opening a specific file or just launching the app as is.

More specifically: A process is started and runs, consuming a ton of CPU cycles. But apart from that nothing visible happens.

### To Reproduce
1. Start the app any way (e.g. via command line `io.elementary.videos`).

### Expected behavior
The app should open within a second and consume virtually no CPU cycles.

### Logs
There is no output whatsoever, when using the command line.

## Platform Information
![Screenshot from 2019-10-06 19-12-11](https://user-images.githubusercontent.com/5802758/66272685-43ea0400-e86d-11e9-900f-b7dd851b836a.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by derkomai** [comment] 2019-10-09 08:05
Same here. In one of my computers (i7 950) I have the exact same behaviour (Videos can't be opened. Icon appears on plack during 25 seconds and then dissapears. If I lauch from terminal, I get the following message at 25s: Failed to register: reached expiration time). In a faster computer (i7 6700K) It seems to eventually open, but usually takes ~20 seconds, after rising the fan speed like crazy.

**Comment by arshubham** [comment] 2019-10-10 13:40
@jtrees Please share the output for `G_MESSAGES_DEBUG=all io.elementary.videos`

**Comment by arshubham** [comment] 2019-10-10 17:07
Yeah seems to be stuck querying the files for library. Can you give the output for `gsettings get io.elementary.videos library-folder`

**Comment by jtrees** [comment] 2019-10-10 17:16
I get the same initial output as @derkomai and haven't been patient enough to wait for the follow-up errors.

Regarding the setting:

```
$ gsettings get io.elementary.videos library-folder
'/home/josh'
```

**Comment by arshubham** [comment] 2019-10-10 17:19
Thanks looks like you are using non standard library path and some file is blocking the library monitoring. You set the path to `/home/josh/Videos` and see if it fixes this for you. I will try to reproduce this on my system.

**Comment by jtrees** [comment] 2019-10-10 17:20
I tried changing the setting to `'/home/josh/Videos'` (which makes more sense) and the player launches again.

So there appear to be two issues here:

1. The default library path isn't optimal.
2. The app doesn't handle folders with a large amount of files well.

**Comment by derkomai** [comment] 2019-10-10 17:23
Yes, in my case it happens exactly the same. By default, every time I've installed elementary OS I've deleted almost all folders in my home dir, including Videos. Could that be the reason why the app is searching inside my home folder?

**Comment by jtrees** [comment] 2019-10-10 17:24
> Yes, in my case it happens exactly the same. By default, every time I've installed elementary OS I've deleted almost all folders in my home dir, including Videos. Could that be the reason why the app is searching inside my home folder?

Now that you mention it, I have also done this. I deleted the folder and replaced it with a symlink.

**Comment by arshubham** [comment] 2019-10-10 17:28
It looks like it defaults to home directory. I was able to partially reproduces the issue. Takes a couple of settings for me (not minutes). Might depend on the size of home directory and type of files. A partial workaround will be to just set the path to an empty folder, small folder you know is working.

**Comment by arshubham** [comment] 2019-10-10 17:33
@jtrees 

> The default library path isn't optimal.

The default Videos folder is fine and set as per XDG special user directories.

> The app doesn't handle folders with a large amount of files well.

This is a valid issue.

**Comment by arshubham** [comment] 2019-10-10 17:40
@derkomai Is it working for you now?

**Comment by derkomai** [comment] 2019-10-10 17:41
@arshubham Yes, perfectly.

**Comment by arshubham** [comment] 2019-10-10 17:42
Great! Can you both tell be what is the size of your home directories? Will make a separate issue for fixing the querying.

**Comment by derkomai** [comment] 2019-10-10 17:52
61.3 GB, 40497 subdirs and 372 868 files according Files. Mostly the snap folder.

**Comment by arshubham** [comment] 2019-10-10 17:57
Thanks. I don't have snaps. Will try with that. Closing this now.

**Closed by arshubham** 2019-10-10 17:57 UTC

**Comment by jtrees** [comment] 2019-10-10 19:16
> Great! Can you both tell be what is the size of your home directories? Will make a separate issue for fixing the querying.

124.3 GB, 163 629 subfolders, 1 238 356 files according to Files (19 files could not be read due to permissions or other errors).
