### ISSUE TITLE
Feature Request : No black bars when resizing elementary videos window

### ISSUE THREAD

**Issue by eric0001** [elementary/videos#231] opened 2021-07-17 21:35 UTC
In elementary OS 6 Beta 2 (Odin) when you open a video file in elementary videos, the video canvas shows the video image and  also black bars on top and on bottom (or black bars on left and on right). The same black bars appear when you resize the window.
Expected behavior would be : just like PiP PictureInPicture resizing behavior. No black bars appearing.
![PiP-resize](https://user-images.githubusercontent.com/39679934/126049781-0b53f529-d715-46a1-800f-e1b9b56827e9.png)
![elementary-videos-no-black-bars](https://user-images.githubusercontent.com/39679934/126210795-5a05d627-3e9c-4e47-b792-a454aba3a4ca.png)

**Comment by danrabbit** [comment] 2021-10-09 17:53
Closing as a duplicate of #83

**Closed by danrabbit** 2021-10-09 17:53 UTC
