### ISSUE TITLE
Video playback is visually distorted and discolored.

### ISSUE THREAD

**Issue by Schyken** [elementary/videos#104] opened 2018-10-22 12:45 UTC
Using elementaryOS Juno, and I've had issues getting playback working in Videos. Audio works fine, but the video is pinkish and pixelated. This happens regardless of format or container. Screenshot for reference:
![image](https://user-images.githubusercontent.com/20944747/47292834-1a34c000-d5bd-11e8-8a9f-249890883ef5.png)

As a side note, I believe it's useful info... I do notice that playback from sites like YouTube in Epiphany also glitch out with the same effects and working audio, so I'm not entirely certain if this would be a Videos specific issue. Willing to provide additional info if requested.

System details as reported by inxi:
System:    Host: schyken-ryzen-horizon Kernel: 4.18.16-041816-generic x86_64 bits: 64 gcc: 8.2.0
           Desktop: Gnome  (Gtk 3.22.30-1ubuntu1) Distro: elementary OS 5.0 Juno
Machine:   Device: desktop Mobo: ASUSTeK model: PRIME B350-PLUS v: Rev X.0x serial: N/A
           UEFI: American Megatrends v: 4011 date: 04/19/2018
CPU:       8 core AMD Ryzen 7 2700 Eight-Core (-MT-MCP-) arch: Zen rev.2 cache: 4096 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm) bmips: 54300
           clock speeds: max: 3400 MHz 1: 1374 MHz 2: 1373 MHz 3: 1374 MHz 4: 1374 MHz 5: 1375 MHz 6: 1373 MHz
           7: 1374 MHz 8: 1374 MHz 9: 1283 MHz 10: 1291 MHz 11: 1301 MHz 12: 1309 MHz 13: 1288 MHz 14: 1270 MHz
           15: 1648 MHz 16: 1678 MHz
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Vega [Radeon RX Vega] bus-ID: 0c:00.0
           Display Server: x11 (X.Org 1.19.6 ) drivers: ati,amdgpu (unloaded: modesetting,fbdev,vesa,radeon)
           Resolution: 2560x1440@59.95hz
           OpenGL: renderer: Radeon RX Vega (VEGA10 / DRM 3.26.0 / 4.18.16-041816-generic, LLVM 6.0.0)
           version: 4.5 Mesa 18.0.5 Direct Render: Yes
Audio:     Card-1 Advanced Micro Devices [AMD] Family 17h (Models 00h-0fh) HD Audio Controller
           driver: snd_hda_intel bus-ID: 0e:00.3
           Card-2 Advanced Micro Devices [AMD/ATI] Device aaf8 driver: snd_hda_intel bus-ID: 0c:00.1
           Card-3 Creative Labs Sound Core3D [Sound Blaster Recon3D / Z-Series]
           driver: snd_hda_intel bus-ID: 09:00.0
           Card-4 Logitech HD Pro Webcam C920 driver: USB Audio usb-ID: 003-002
           Card-5 C-Media driver: USB Audio usb-ID: 001-002
           Sound: Advanced Linux Sound Architecture v: k4.18.16-041816-generic
Network:   Card: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
           driver: r8169 v: 2.3LK-NAPI port: f000 bus-ID: 04:00.0
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: <filter>
Drives:    HDD Total Size: 2250.5GB (2.9% used)
           ID-1: /dev/nvme0n1 model: Samsung_SSD_960_EVO_250GB size: 250.1GB
           ID-2: /dev/sda model: WDC_WDS500G2B0A size: 500.1GB temp: 26C
           ID-3: /dev/sdb model: WDC_WDS500G2B0A size: 500.1GB temp: 24C
           ID-4: /dev/sdc model: WDC_WDS500G2B0A size: 500.1GB temp: 25C
           ID-5: /dev/sdd model: WDC_WDS500G2B0A size: 500.1GB temp: 26C
Partition: ID-1: / size: 231G used: 20G (9%) fs: xfs dev: /dev/nvme0n1p3
           ID-2: /boot size: 946M used: 153M (18%) fs: ext4 dev: /dev/nvme0n1p2
RAID:      No RAID devices: /proc/mdstat, md_mod kernel module present
Sensors:   System Temperatures: cpu: N/A mobo: N/A gpu: 36.0
           Fan Speeds (in rpm): cpu: 0
Info:      Processes: 426 Uptime: 1 day Memory: 4153.3/32165.8MB Init: systemd runlevel: 5 Gcc sys: 7.3.0
           Client: Shell (bash 4.4.191) inxi: 2.3.56

**Comment by peteruithoven** [comment] 2019-02-06 23:07
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/videos/issues/102

**Closed by peteruithoven** 2019-02-06 23:07 UTC
Labels: Status: Duplicate
