### ISSUE TITLE
Problems using Videos app in a big screen computer.

### ISSUE THREAD

**Issue by luishenriquetp** [elementary/videos#208] opened 2020-08-12 19:22 UTC
## Describe the bug
The Video app is delaying the frames in ElementaryOS running on an iMac with a large screen.

### To Reproduce
I just run ElementaryOS in an iMac with a big screen, tried to use Videos app to see a video and the reproduction worked like a slideshow. It was showing frame to frame. The sound worked normally. Note that I use ElementaryOS and Videos in a notebook with a small screen and this problem doesn't happen.

### Expected behavior
Expected to see a video reproduction with perfection, but it was not possible.

### Platform Information
 - OS: ElementaryOS
 - OS Version: Hera
 - Hardware: iMac
 - Screenshot:

![Screenshot from 2020-08-12 16-17-46](https://user-images.githubusercontent.com/13193188/90058120-b1e62f80-dcb7-11ea-83ec-da8355ac761c.png)

- [X] I'm using the latest released stable version

**Comment by kdwk** [comment] 2021-09-18 12:54
The latest release is now elementary OS 6 Odin. Please check to see if the issue is still present in Odin.

**Comment by danirabbit** [comment] 2023-07-08 15:32
afaict video performance is still good even on a large display here. Maybe also fixed by #335?

**Closed by danirabbit** 2023-07-08 15:32 UTC
