### ISSUE TITLE
Sometimes showing white screen or stop playing video

### ISSUE THREAD

**Issue by xic3fox** [elementary/videos#119] opened 2019-02-10 20:40 UTC
There are 2 issues I have discovered.
First issue:
When I play videos in mp4 format, the player sometimes stop playing the video sequence while it still plays the audio. Then I can either wait for a while (its kinda random how long I have to wait) or I move the mouse (doesn't matter how much), then the video continues playing.
The second issue is a white screen zhat appears sometimes when I want to play a video (also in mp4 format). How I try to start the video doesn't matter, either I select the video file from within the file browser or I select it from within the video app. I don't see anything like a pattern when the white screen appears. It's kinda like the first issue, that's why I put them both im one issue.

**Comment by peteruithoven** [comment] 2019-02-10 20:44
Thanks for the report! I'm afraid the first issue is a duplicate of https://github.com/elementary/os/issues/121
I assume https://github.com/elementary/videos/issues/115 is a duplicate of the second, although the color is different. 

I'd recommend using another video player for now.

**Closed** 2019-02-10 20:45 UTC
Labels: Status: Duplicate
