### ISSUE TITLE
The seek bar moves slightly offset to the mouse pointer when clicked or dragged

### ISSUE THREAD

**Issue by cryptowyrm** [elementary/videos#103] opened 2018-10-21 20:33 UTC
When you play a video in the Videos app and click (or drag) on the seek bar to jump to a specific position in the video, the seek bar jumps slightly to the left or the right of the mouse pointer. The offset seems to get bigger the further towards the left or the right of the seek bar you click and goes away as you move towards the middle of the seek bar, here is a GIF animation of the problem:

![peek 2018-10-21 22-07](https://user-images.githubusercontent.com/16908445/47272010-c48df280-d57f-11e8-8464-57367f9fbfd3.gif)

The volume slider in elementary OS has the same issue, it's less visible there since the slider is so short. I'm not sure if it uses the same GTK widget since it looks very different, so maybe this issue isn't specific to the Videos app.

In case this only happens on my computer, I'm using an Acer C720 Chromebook with elementary OS 5 Juno, it has an Intel graphics chip.

**Comment by danrabbit** [comment] 2018-12-18 17:54
Closing as a duplicate of https://github.com/elementary/stylesheet/pull/301

**Closed by danrabbit** 2018-12-18 17:54 UTC
