### ISSUE TITLE
Can not seek videos with mouse click

### ISSUE THREAD

**Issue by iamantu93** [elementary/videos#109] opened 2018-11-25 12:45 UTC
Clicking progress bar stops video. But left right arrow keys to seek is working fine

**Comment by arshubham** [comment] 2019-10-22 13:02
@iamantu93  Can you elaborate and share the video file. Unable to reproduce the issue at my end.

**Comment by arshubham** [comment] 2019-11-08 05:19
Closing since OP has not responded. Will reopen if the issue persists.

**Closed by arshubham** 2019-11-08 05:19 UTC
Labels: Status: Incomplete
