### ISSUE TITLE
It is not a good behavior for a video player to let the screen turn off during playback. Built-in video player of elementary os. It needs a fix. I know I can always use VLC player.

### ISSUE THREAD

**Issue by koofejood** [elementary/videos#212] opened 2020-09-16 09:28 UTC
## Prerequisites
- [ ] I have searched open and closed issues for duplicates.

## Describe the bug

If applicable, add screenshots or screen recordings to help explain your problem.

## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version

**Comment by danrabbit** [comment] 2020-09-16 15:02
This may have been resolved by David's recent work in Gala. Worth testing in 5.x and 6 to see if it's been resolved outside of Videos

**Comment by jeremypw** [comment] 2020-09-16 15:05
Not sure why we are using the "org.freedesktop.ScreenSaver" interface rather than `Gtk.Application.inhibit ()` - of course there is no guarantee the window manager will honor the request either way I guess.   I'll check it out in Odin.

**Comment by jeremypw** [comment] 2020-09-16 15:37
Seems Gala has discontinued supplying the "org.freedesktop.ScreenSaver" interface so that would explain why Videos can no longer inhibit the screen blanking on "idle".   I guess we will have to switch the interface used.   I tested Videos on Ubuntu Focal and it inhibits sceen blanking there presumably because the freedesktop interface is supplied.

**Comment by davidmhewitt** [comment] 2020-09-16 15:53
I have tested this works on 6.0. Gala doesn’t need to supply the screensaver interface because there is a gsd screensaver proxy plugin that does it and proxies the calls to gala.

It may be possible to use Gtk.Application.inhibit now but I know that never used to work for some reason.

As for why this isn’t working in 5.x, I’m not sure. Afaik we haven’t released any of the new gala screensaver stuff there that could have affected this.

**Comment by danrabbit** [comment] 2020-09-16 15:58
Based on some other reports, I think screen inhibiting has been broken in 5.x for a while.

I'll propose a branch using Gtk.Application.Inhibit and see if that changes anything :)

**Comment by jeremypw** [comment] 2020-09-16 16:00
I was wondering whether we should inhibit "suspend" (which can also happen on inactivity) as well - or does the screensaver interface already do that?

**Comment by danrabbit** [comment] 2020-09-16 16:02
Depends which flags you send :) https://valadoc.org/gtk+-3.0/Gtk.ApplicationInhibitFlags.html

**Comment by jeremypw** [comment] 2020-09-16 16:07
Yes, but does the existing method (using the screensaver DBus interface) already do it?  If not it would be a reason to change to Application.inhibit () - if it works.

**Comment by danrabbit** [comment] 2020-09-16 16:21
It looks like the existing code includes the suspend flag but not idle

**Comment by jeremypw** [comment] 2020-09-16 16:27
Just tried Videos in Odin in VirtualBox and got the terminal warning 
`Inhibitor.vala:66: Could not inhibit screen: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
`
which does not look to promising ...

**Comment by davidmhewitt** [comment] 2020-09-16 17:08
@jeremypw This is why inhibit isn't working in Odin:
https://github.com/elementary/session-settings/pull/37/files

I'd made some changes to session settings that never built due to a missing dependency. Once the daily recipe runs and the new version is available in launchpad, it should be working.

**Closed** 2020-09-17 16:58 UTC
Labels: Status: In Progress

**Comment by o-alquimista** [comment] 2022-01-18 04:46
I can reproduce this on Jólnir.

io.elementary.videos v2.8.3
