### ISSUE TITLE
Not working with big video files

### ISSUE THREAD

**Issue by DanilChechkov** [elementary/videos#197] opened 2020-05-04 10:33 UTC
AMD R5 M400 series - big files work with very low fps, about one picture in half of a minute. With VLC player big files ok. With small files ok too, btw, thank you for awesome system and support. Stay same cool

**Comment by jeremypw** [comment] 2020-05-04 11:08
How big is big? And what format?

**Comment by DanilChechkov** [comment] 2020-05-04 11:12
Mean full hd video, 5gb 50minutes .mkv file

**Comment by DanilChechkov** [comment] 2020-05-04 11:15
I can make a video recording if it will be helpful, right now elementary OS moving to a new SSD hehe, give me some time))

**Comment by jeremypw** [comment] 2020-05-04 11:40
The nearest I have is a 6.8GB .mkv file. `mediainfo` indicated the video codec ID was V_MPEG4/ISO/AVC . Resolution 1920 x 1080.  Audio format AC-3

This played at the expected speed on an i5 laptop with 8GB memory using the master version of Videos.

Please give more information about the machine specs and the version of the OS and Videos you are using.

**Comment by DanilChechkov** [comment] 2020-05-05 10:25
CPU: AMD A9-9420 2 cores
GPU: AMD Radeon R5 m400 series
RAM: 8GB
That's my laptop. About video:
Codec: H264 - MPEG-4 AVC (part 10) (avc1)
Resolution: 1920x960
FPS: 25
Audio codec: A52 Audio (aka AC3) (a52 )
Os now at SSD, video at HDD connected with USB 3.0

**Comment by DanilChechkov** [comment] 2020-05-05 10:31
Uploading video at GDrive. First one - playing with video, second with vlc, hope you will see freezes and difference between same part of video

**Comment by DanilChechkov** [comment] 2020-05-05 10:49
https://drive.google.com/file/d/1Vzjp-9QMoBBy65n2N2Hosr5Dkm8XDXrm/view?usp=drivesdk

Video is here. I’m sorry to make u wait, hope that will make sense

**Comment by DanilChechkov** [comment] 2020-05-05 11:15
Oh elementary OS version is 5.1.4 Hera

**Comment by Cjnator38** [comment] 2020-05-27 03:45
Same thing happens with me. This also causes the display to flicker and the entire OS to lock up.
GPU: 4GB AMD Radeon R7 360
CPU: Intel Pentium G3420 @ 3.2 GHz

**Comment by Cjnator38** [comment] 2020-05-27 03:46
I've tested VLC with the same video I have used and it worked flawlessly

**Comment by jeremypw** [comment] 2020-05-27 10:33
I recently found that a different bug with Videos was related to Bionic GStreamer and the Bionic Intel graphics driver.  The bug did not occur on my machine with NVidia graphics (or in player that did not use GStreamer).  The exact cause has not been found but it was solved by updating the driver to the latest version.

**Comment by jeremypw** [comment] 2020-05-28 11:09
I suspect that video acceleration is not working for your setup.  Make sure you the have `va-driver-all`  and `vdpau-driver-all` packages installed to make sure that you have the acceleration drivers available in Bionic.  If the problem is with GStreamer compatibility for your particular cards, you may have to wait for the next release of  of elementary, with more up to date drivers and libraries, unless you can install them yourselves :-(

VLC does not use GStreamer, I believe, so may have better compatibility.

**Comment by Cjnator38** [comment] 2020-05-29 14:26
Well, I'll just continue using VLC until this gets fixed.

**Comment by danirabbit** [comment] 2024-06-05 19:34
Closing since this is related to a very old version with a different codec situation and this has definitely been resolved

**Closed by danirabbit** 2024-06-05 19:34 UTC
