### ISSUE TITLE
The main player does not play

### ISSUE THREAD

**Issue by RoVlaTi** [elementary/videos#102] opened 2018-10-01 10:30 UTC
![2018-10-01 13-25-56](https://user-images.githubusercontent.com/43745798/46283649-a5520580-c57d-11e8-93ce-a2b2efe6e495.png)
![2018-10-01 13-11-52](https://user-images.githubusercontent.com/43745798/46283655-a97e2300-c57d-11e8-85b4-2d142bdd5f03.png)
![2018-10-01 13-29-44](https://user-images.githubusercontent.com/43745798/46283779-1db8c680-c57e-11e8-89c4-6a79b4e60eb6.png)

**Comment by aadilayub** [comment] 2018-10-20 04:59
Video playback is similarly broken on Epiphany as well, whereas everything works fine on VLC and Firefox.

![screenshot from 2018-10-19 18 52 08](https://user-images.githubusercontent.com/31581044/47251612-fd3aa880-d467-11e8-93d4-3f632290165e.png)
![screenshot from 2018-10-20 12 59 21](https://user-images.githubusercontent.com/31581044/47251613-00359900-d468-11e8-88a6-e782f032b44c.png)

**Comment by aadilayub** [comment] 2018-10-22 03:32
Update: Playing .webm videos seems to work. mp4 and mkv videos are broken as illustrated in screenshots above.

![screenshot from 2018-10-22 11-30-10](https://user-images.githubusercontent.com/31581044/47276976-f8076600-d5ed-11e8-9555-b4ee8d93bd60.png)

**Comment by aadilayub** [comment] 2018-10-22 03:33
Update: Playing .webm videos seems to work. mp4 and mkv videos are broken as illustrated in screenshots above.

![screenshot from 2018-10-22 11-30-10](https://user-images.githubusercontent.com/31581044/47276976-f8076600-d5ed-11e8-9555-b4ee8d93bd60.png)

**Comment by aadilayub** [comment] 2018-10-22 05:14
After reading https://github.com/artemanufrij/playmyvideos/issues/31, I believe installing `ubuntu-restricted-extras` causes the issue. However, the issue persists even after uninstalling the package.

**Comment by arshubham** [comment] 2019-10-12 12:35
@aadilayub @RoVlaTi Are you still experiencing this issue? Installing `ubuntu-restricted-extras` also installs `libavcodec-extra` and `libavcodec-extra57`. They might not be automatically installed on removing `ubuntu-restricted-extras`

**Comment by aadilayub** [comment] 2019-10-13 07:47
Hey @arshubham. I can't confirm because I've shifted to a Fedora system. I think I performed a clean install of Juno at some point and these issues went away.

**Comment by danirabbit** [comment] 2024-06-05 19:38
Closing since this seems related to an old GStreamer version and is no longer reproducible

**Closed by danirabbit** 2024-06-05 19:38 UTC
