### ISSUE TITLE
DVD playing but with wrong aspect ratio 4:3 instead of 16:9

### ISSUE THREAD

**Issue by eric0001** [elementary/videos#82] opened 2018-05-27 21:29 UTC
Once I am able to start a DVD movie in audience (aka pantheon-videos), I can see the trailer or the animated DVD menu with the wrong aspect ratio 4:3 instead of 16:9

**Comment by davidmhewitt** [comment] 2019-05-22 11:23
Thanks for the report!

This is likely caused by #108, I'll close this issue in favor of that one as it has more information.

**Closed by davidmhewitt** 2019-05-22 11:23 UTC
