### ISSUE TITLE
CPU usage when on pause

### ISSUE THREAD

**Issue by Philosoft** [elementary/videos#56] opened 2018-01-20 11:50 UTC
Here is screenshot of htop with 2 process audience (videos) and mplayer which have opened same file (1080p if it has some importance, but situation exactly the same for any video I have) [audience constant cpu usage](https://drive.google.com/open?id=1iJ02m5r-Tf3B8i95l2_4U-CEJ4Z-tzr-)

* both players opened on separate workspaces
* both fullscreen
* both on pause approx after 1s after video starts playing

audience (videos) has constant cpu usage from 5 (min) to 10 (max) and approx 7.8%

If you need any more info - provide instructions how to gather it and I will send it)

**Comment by arshubham** [comment] 2019-10-24 05:33
@Philosoft Can you still reproduce this issue in juno? Unable to reproduce on my end. Might have been fixed with base update to 18.04

**Comment by Philosoft** [comment] 2019-10-24 05:48
I no longer use elementary, so - no. Feel free to close this, since there no comments supporting this

**Closed** 2019-10-24 05:58 UTC
Labels: Status: Incomplete
