### ISSUE TITLE
Videos play with sound but only a black screen.

### ISSUE THREAD

**Issue by KaiTebay** [elementary/videos#286] opened 2021-12-13 11:24 UTC
### What Happened?

I can open Videos and play files from the video library, or open video files with Videos from the Files app. 

Video files begin playback; the titlebar updates to show the correct name; player controls work as expected (including seek, pause/resume, and current/total running time); and sound works as expected.

However, most videos only show a black screen. 

Unlike #237:

- Sound works.
- Installing `ubuntu-restricted-extras` does not fix the problem.

Some video files (some .mkv files) _do_ play as expected. Other .mkv files and all .mp4 files encounter the described issue. I have not tested other file formats.

All the video files which are unplayable in Videos play as expected in VLC Media Player (Flatpak).

### Steps to Reproduce

1. Open video file using video library or using the 'open with' context-menu option, from Files.
2. The video plays with sound but no image. ![Screenshot from 2021-12-13 11-15-20](https://user-images.githubusercontent.com/95620167/145802771-2fef935b-2b66-4734-b4a4-fde5f4525c74.png)

### Expected Behavior

**Expected**: video plays with sound and image.
**Actual**: video plays with sound but no image.

### OS Version

6.x (Odin)

### Software Version

Latest release (I have run all updates)

### Hardware Info

**Hardware**:
- Razer Blade 15 (Base Model)
- Hexa-Core Intel® Core™ i7-8750H CPU @ 2.20GHz
- Intel® UHD Graphics 630 (Mobile)
- NVIDIA® GeForce® GTX® 1060 Mobile
- 15.5 GiB memory
- 978.6 GB storage

**Software**:
- Latest version of elementaryOS.
- Latest version of all software.
- NVIDIA 470 driver from AppCenter (correct version for GPU).

**Setup & Notes:**
- Connected to an external display via HDMI, using NVIDIA card as primary display source.
- No notable custom configurations.

**Comment by meisenzahl** [comment] 2021-12-13 11:30
Closing as a duplicate of #281. Should hopefully be fixed by #285. If this will not fix your problem, feel free to reopen.

**Closed by meisenzahl** 2021-12-13 11:30 UTC

**Comment by KaiTebay** [comment] 2021-12-16 09:21
> Closing as a duplicate of #281. Should hopefully be fixed by #285. If this will not fix your problem, feel free to reopen.

Thanks so much! And apologies, I didn't see that issue.
