### ISSUE TITLE
videos program not work

### ISSUE THREAD

**Issue by xGoatAlpha** [elementary/videos#118] opened 2019-02-06 23:04 UTC
The program videos is no longer working after a clean install, tried uninstall reinstall to no avail. The screen is just a blur of psychedelic pink and purple mess. Vlc and other players work fine

**Comment by peteruithoven** [comment] 2019-02-06 23:08
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/videos/issues/102

**Closed by peteruithoven** 2019-02-06 23:08 UTC
Labels: Status: Duplicate
